# Generated by Django 4.2.2 on 2023-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_emailotp_enquiryemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
