# Generated by Django 3.2.8 on 2022-02-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentTable',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('stu_marks', models.CharField(max_length=10)),
            ],
        ),
    ]
